// --------------------------------------------------------------------------------------------------------------------
// <copyright company="Aspose Pty Ltd" file="StorageApiTests.cs">
//   Copyright (c) 2018 GroupDocs.Storage for Cloud
// </copyright>
// <summary>
//   Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
// 
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
// 
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

using GroupDocs.Storage.Cloud.Sdk.Api;
using GroupDocs.Storage.Cloud.Sdk.Model;
using GroupDocs.Storage.Cloud.Sdk.Model.Requests;
using GroupDocs.Storage.Cloud.Sdk.Test.Base;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.IO;

namespace GroupDocs.Storage.Cloud.Sdk.Test
{
    /// <summary>
    ///  Class for testing StorageApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestClass]
    public class StorageApiTests : BaseTestContext
    {
        private readonly string dataFolder = BaseTestDataPath;
        private readonly string storageName = "StorageName";

        /// <summary>
        /// Test StorageGetDiscUsage
        /// </summary>
        [TestMethod]
        public void StorageGetDiscUsageTest()
        {
            GetDiscUsageRequest request = new GetDiscUsageRequest();
            request.storage = storageName;
            var response = StorageApi.GetDiscUsage(request);
            Assert.AreEqual(200, response.Code);
        }

        /// <summary>
        /// Test StorageGetIsExist
        /// </summary>
        [TestMethod]
        public void StorageGetIsExistTest()
        {
            GetIsExistRequest request = new GetIsExistRequest();
            request.path = Path.Combine(dataFolder, "folder1");
            request.storage = storageName;
            request.versionId = null;
            var response = StorageApi.GetIsExist(request);
            Assert.AreEqual(200, response.Code);
            Assert.IsTrue(Convert.ToBoolean(response.FileExist.IsExist));
        }

        /// <summary>
        /// Test StorageGetIsStorageExist
        /// </summary>
        [TestMethod]
        public void StorageGetIsStorageExistTest()
        {
            GetIsStorageExistRequest request = new GetIsStorageExistRequest();
            request.name = storageName;
            var response = StorageApi.GetIsStorageExist(request);
            Assert.AreEqual(200, response.Code);
            Assert.IsTrue(Convert.ToBoolean(response.IsExist));
        }

        /// <summary>
        /// Test StorageGetListFileVersions
        /// </summary>
        [TestMethod]
        public void StorageGetListFileVersionsTest()
        {
            GetListFileVersionsRequest request = new GetListFileVersionsRequest();
            request.path = "folder2/TestFile1.pdf";
            request.storage = storageName;
            var response = StorageApi.GetListFileVersions(request);
            Assert.AreEqual(200, response.Code);
            Assert.IsNotNull(response.FileVersions);
        }

    }

}
